{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "declaration": true,
    "experimentalDecorators": true,
    "downlevelIteration": true,
    "importHelpers": true,
    "jsx": "react",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": false,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "skipLibCheck": true,
    "strictFunctionTypes": true,
    "target": "es5",
    "module": "esnext",
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015.core",
      "es2015.collection",
      "es2015.symbol",
      "es2015.iterable",
      "es2015.promise",
      "es2016.array.include"
    ],
    "types": ["jest", "react","react-router","history", "enzyme", "css-color-names", "jest-styled-components", "styled-components"],
    "typeRoots": ["./typings", "./node_modules/@types"]
  },
  "files": [
    "./typings/atlaskit.d.ts",
    "./typings/deep-equal.d.ts",
    "./typings/deepcopy.d.ts",
    "./typings/events.d.ts",
    "./typings/jest-in-case.d.ts",
    "./typings/jest.frameworkSetup.d.ts",
    "./typings/json.d.ts",
    "./typings/lodash.debounce.d.ts",
    "./typings/lodash.last.d.ts",
    "./typings/lodash.matches.d.ts",
    "./typings/lodash.merge.d.ts",
    "./typings/node.d.ts",
    "./typings/package.json.d.ts",
    "./typings/pdfjs-dist.d.ts",
    "./typings/postis.d.ts",
    "./typings/prosemirror-markdown.d.ts",
    "./typings/rusha.d.ts",
    "./typings/scrollparent.d.ts",
    "./typings/snake-case.d.ts",
    "./typings/static-assets.d.ts",
    "./typings/url.d.ts",
    "./typings/uuid.d.ts",
    "./typings/webpack.d.ts"
  ]
}
