/* tslint:disable:variable-name */
import * as tslib_1 from "tslib";
import styled from 'styled-components';
import { colors } from '@uidu/theme';
export var FilmStripViewWrapper = styled.div(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  position: relative;\n  padding: 3px 0;\n  border-radius: 3px;\n\n  &:hover .arrow {\n    opacity: 1;\n  }\n\n  .ellipsed-text {\n    white-space: initial;\n  }\n"], ["\n  position: relative;\n  padding: 3px 0;\n  border-radius: 3px;\n\n  &:hover .arrow {\n    opacity: 1;\n  }\n\n  .ellipsed-text {\n    white-space: initial;\n  }\n"])));
export var FilmStripListWrapper = styled.div(templateObject_2 || (templateObject_2 = tslib_1.__makeTemplateObject(["\n  width: inherit;\n  overflow: hidden;\n  padding: 2px 0;\n"], ["\n  width: inherit;\n  overflow: hidden;\n  padding: 2px 0;\n"])));
export var FilmStripList = styled.ul(templateObject_3 || (templateObject_3 = tslib_1.__makeTemplateObject(["\n  margin: 0;\n  padding: 0;\n  transition-property: transform;\n  transition-timing-function: cubic-bezier(0.77, 0, 0.175, 1);\n  white-space: nowrap;\n  display: inline-block;\n"], ["\n  margin: 0;\n  padding: 0;\n  transition-property: transform;\n  transition-timing-function: cubic-bezier(0.77, 0, 0.175, 1);\n  white-space: nowrap;\n  display: inline-block;\n"])));
export var FilmStripListItem = styled.li(templateObject_4 || (templateObject_4 = tslib_1.__makeTemplateObject(["\n  list-style-type: none;\n  margin: 0;\n  padding: 0 4px;\n  display: inline-block;\n  vertical-align: middle;\n  /* Fixes issue with child Cards using inline-block */\n  font-size: 0;\n"], ["\n  list-style-type: none;\n  margin: 0;\n  padding: 0 4px;\n  display: inline-block;\n  vertical-align: middle;\n  /* Fixes issue with child Cards using inline-block */\n  font-size: 0;\n"])));
export var ArrowWrapper = styled.div(templateObject_5 || (templateObject_5 = tslib_1.__makeTemplateObject(["\n  position: absolute;\n  top: 50%;\n  transform: translateY(-50%);\n  background-color: ", ";\n  border-radius: 100%;\n  display: flex;\n  cursor: pointer;\n  transition: opacity 0.3s;\n  box-shadow: 0 1px 6px 0 rgba(0, 0, 0, 0.6);\n  color: black;\n  width: 30px;\n  height: 30px;\n  justify-content: center;\n  opacity: 0;\n\n  &:hover {\n    color: black;\n    background-color: ", ";\n  }\n\n  &:active {\n    color: ", ";\n    background-color: ", ";\n  }\n\n  svg {\n    height: 30px;\n    width: 20px;\n  }\n"], ["\n  position: absolute;\n  top: 50%;\n  transform: translateY(-50%);\n  background-color: ", ";\n  border-radius: 100%;\n  display: flex;\n  cursor: pointer;\n  transition: opacity 0.3s;\n  box-shadow: 0 1px 6px 0 rgba(0, 0, 0, 0.6);\n  color: black;\n  width: 30px;\n  height: 30px;\n  justify-content: center;\n  opacity: 0;\n\n  &:hover {\n    color: black;\n    background-color: ", ";\n  }\n\n  &:active {\n    color: ", ";\n    background-color: ", ";\n  }\n\n  svg {\n    height: 30px;\n    width: 20px;\n  }\n"])), colors.N20, colors.N40, colors.B400, colors.B50);
export var ArrowLeftWrapper = styled(ArrowWrapper)(templateObject_6 || (templateObject_6 = tslib_1.__makeTemplateObject(["\n  left: 8px;\n\n  svg {\n    padding-right: 2px;\n  }\n"], ["\n  left: 8px;\n\n  svg {\n    padding-right: 2px;\n  }\n"])));
export var ArrowRightWrapper = styled(ArrowWrapper)(templateObject_7 || (templateObject_7 = tslib_1.__makeTemplateObject(["\n  right: 8px;\n\n  svg {\n    padding-left: 1px;\n  }\n"], ["\n  right: 8px;\n\n  svg {\n    padding-left: 1px;\n  }\n"])));
export var Shadow = styled.div(templateObject_8 || (templateObject_8 = tslib_1.__makeTemplateObject(["\n  position: absolute;\n  z-index: 10;\n  height: 100%;\n  top: 0;\n  width: 2px;\n  background-color: rgba(0, 0, 0, 0.2);\n"], ["\n  position: absolute;\n  z-index: 10;\n  height: 100%;\n  top: 0;\n  width: 2px;\n  background-color: rgba(0, 0, 0, 0.2);\n"])));
export var ShadowLeft = styled(Shadow)(templateObject_9 || (templateObject_9 = tslib_1.__makeTemplateObject(["\n  left: 0;\n"], ["\n  left: 0;\n"])));
export var ShadowRight = styled(Shadow)(templateObject_10 || (templateObject_10 = tslib_1.__makeTemplateObject(["\n  right: 0;\n"], ["\n  right: 0;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10;
//# sourceMappingURL=styled.js.map