import { AlterProps, BuildProps } from './types';
import { BlockCardResolvedViewProps } from '@uidu/media-ui';
export declare type AlterPropsRepository = AlterProps<BlockCardResolvedViewProps>;
export declare type BuildPropsRepository = BuildProps<BlockCardResolvedViewProps>;
export declare const buildRepositoryLink: BuildPropsRepository;
export declare const buildRepositoryTitle: BuildPropsRepository;
export declare const buildRepositoryDescription: BuildPropsRepository;
export declare const buildRepositoryByline: BuildPropsRepository;
export declare const setRepositoryContext: AlterPropsRepository;
export declare const setRepositoryDetails: AlterPropsRepository;
export declare function extractPropsFromSourceCodeRepository(json: any): BlockCardResolvedViewProps;
