import * as tslib_1 from "tslib";
import styled from 'styled-components';
import { colors } from '@uidu/theme';
console.log(colors);
export var StyledStepNumber = styled.div(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  align-items: center;\n  justify-content: center;\n  display: flex;\n  background-color: ", ";\n  border-radius: 0.25rem;\n  color: ", ";\n  font-weight: bold;\n  height: 2rem;\n  text-align: center;\n  width: 2rem;\n  transition: background-color 300ms linear;\n"], ["\n  align-items: center;\n  justify-content: center;\n  display: flex;\n  background-color: ", ";\n  border-radius: 0.25rem;\n  color: ", ";\n  font-weight: bold;\n  height: 2rem;\n  text-align: center;\n  width: 2rem;\n  transition: background-color 300ms linear;\n"])), colors.N30, colors.N0);
export var StyledStepHeader = styled.div(templateObject_2 || (templateObject_2 = tslib_1.__makeTemplateObject(["\n  background-color: white;\n  cursor: pointer;\n  outline: none;\n  text-decoration: none;\n\n  &:hover {\n    text-decoration: none;\n  }\n"], ["\n  background-color: white;\n  cursor: pointer;\n  outline: none;\n  text-decoration: none;\n\n  &:hover {\n    text-decoration: none;\n  }\n"])));
export var StyledStepBody = styled.div(templateObject_3 || (templateObject_3 = tslib_1.__makeTemplateObject(["\n  font-size: 0;\n  background-color: ", ";\n  margin: 0;\n  opacity: 0;\n  padding-bottom: 1rem;\n  padding-left: 1rem;\n  padding-right: 1rem;\n  padding-top: 1rem;\n  position: relative;\n  transition: font-size 0.25s, padding 0.25s, opacity 0.5s 0.25s;\n"], ["\n  font-size: 0;\n  background-color: ", ";\n  margin: 0;\n  opacity: 0;\n  padding-bottom: 1rem;\n  padding-left: 1rem;\n  padding-right: 1rem;\n  padding-top: 1rem;\n  position: relative;\n  transition: font-size 0.25s, padding 0.25s, opacity 0.5s 0.25s;\n"])), colors.N0);
export default styled.div(templateObject_4 || (templateObject_4 = tslib_1.__makeTemplateObject(["\n  position: relative;\n\n  &.disabled {\n    pointer-events: none;\n\n    .step-button {\n      .step-number {\n        background-color: ", ";\n        transition: background-color 300ms linear;\n      }\n\n      .step-title {\n        opacity: 0.3;\n      }\n    }\n  }\n\n  &.active {\n    .step-body {\n      font-size: 1rem;\n      opacity: 1;\n      padding-bottom: 2rem;\n      transition: font-size 0.25s, padding 0.25s, opacity 0.5s 0.25s;\n    }\n  }\n\n  &::after {\n    background-color: ", ";\n    content: '';\n    height: 100%;\n    left: calc(2rem - 1px);\n    position: absolute;\n    top: 32px;\n    width: 1px;\n    z-index: -1;\n  }\n"], ["\n  position: relative;\n\n  &.disabled {\n    pointer-events: none;\n\n    .step-button {\n      .step-number {\n        background-color: ", ";\n        transition: background-color 300ms linear;\n      }\n\n      .step-title {\n        opacity: 0.3;\n      }\n    }\n  }\n\n  &.active {\n    .step-body {\n      font-size: 1rem;\n      opacity: 1;\n      padding-bottom: 2rem;\n      transition: font-size 0.25s, padding 0.25s, opacity 0.5s 0.25s;\n    }\n  }\n\n  &::after {\n    background-color: ", ";\n    content: '';\n    height: 100%;\n    left: calc(2rem - 1px);\n    position: absolute;\n    top: 32px;\n    width: 1px;\n    z-index: -1;\n  }\n"])), colors.N30, colors.N30);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=Step.js.map