import * as tslib_1 from "tslib";
import styled from 'styled-components';
import { colors } from '@uidu/theme';
export var IconWrapper = styled.div(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  color: ", ";\n  display: flex;\n  align-items: center;\n  justify-content: center;\n\n  > span {\n    width: 120px;\n    height: 120px;\n\n    svg {\n      width: 100%;\n      height: 100%;\n    }\n  }\n"], ["\n  color: ", ";\n  display: flex;\n  align-items: center;\n  justify-content: center;\n\n  > span {\n    width: 120px;\n    height: 120px;\n\n    svg {\n      width: 100%;\n      height: 100%;\n    }\n  }\n"])), colors.N30);
export var ButtonWrapper = styled.div(templateObject_2 || (templateObject_2 = tslib_1.__makeTemplateObject(["\n  text-align: center;\n"], ["\n  text-align: center;\n"])));
export var TextDescription = styled.div(templateObject_3 || (templateObject_3 = tslib_1.__makeTemplateObject(["\n  margin-top: 18px;\n  color: ", ";\n  opacity: 0.7;\n  font-size: 12px;\n  text-align: center;\n"], ["\n  margin-top: 18px;\n  color: ", ";\n  opacity: 0.7;\n  font-size: 12px;\n  text-align: center;\n"])), colors.N500);
export var Title = styled.div(templateObject_4 || (templateObject_4 = tslib_1.__makeTemplateObject(["\n  text-align: center;\n  font-size: 16px;\n  color: ", ";\n"], ["\n  text-align: center;\n  font-size: 16px;\n  color: ", ";\n"])), colors.N100);
export var ConnectWrapper = styled.div(templateObject_5 || (templateObject_5 = tslib_1.__makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  justify-content: center;\n  height: 100%;\n"], ["\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  justify-content: center;\n  height: 100%;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
//# sourceMappingURL=styled.js.map