import {
  AttributeSpec,
  MarkSpec,
  Node,
  NodeSpec,
  ParseRule,
  Schema,
} from 'prosemirror-model';
import { createSchema, paragraph } from '../src/schema';

export { Node, Schema };
export type { AttributeSpec, MarkSpec, NodeSpec, ParseRule };
export default createSchema({
  nodes: [
    'doc',
    'paragraph',
    'text',
    'bulletList',
    'orderedList',
    'listItem',
    'heading',
    'blockquote',
    'codeBlock',
    'panel',
    'rule',
    'hardBreak',
    'mention',
    'emoji',
    'image',
    'media',
    'mediaGroup',
    'confluenceJiraIssue',
    'mediaSingle',
    'plain',
    'table',
    'tableCell',
    'tableHeader',
    'tableRow',
    'extension',
    'inlineExtension',
    'bodiedExtension',
    'date',
    'unknownBlock',
    'placeholder',
    'inlineCard',
    'blockCard',
    'unsupportedBlock',
    'unsupportedInline',
  ],
  marks: [
    'em',
    'strong',
    'code',
    'strike',
    'underline',
    'link',
    'subsup',
    'textColor',
  ],
  customNodeSpecs: {
    plain: { ...paragraph, content: 'text*', marks: '' },
  },
});
