import * as React from 'react';
import { useClipboard } from 'use-clipboard-copy';
import ChatWindow from '../src';

interface GitHubJSONResponse {
  items: Array<any>;
}

function fetchUsers(query: string, callback: () => void): any {
  if (!query) {
    return Promise.resolve([]);
  }

  return (
    fetch(`https://api.github.com/search/users?q=${query}`)
      .then((response: Response) => response.json())
      // Transform the users to what react-mentions expects
      .then((json: GitHubJSONResponse) =>
        json.items.map(user => ({ display: user.login, id: user.login })),
      )
      .then(callback)
      .catch(() => [])
  );
}

export default function Basic() {
  const clipboard = useClipboard({
    copiedTimeout: 1500,
  });
  return (
    <ChatWindow
      isSelf={messager => messager.id === 1306}
      betweenMinutes={20}
      mentionables={[
        {
          trigger: '@',
          type: 'User',
          data: fetchUsers,
        },
      ]}
      actions={({ setEditing, message }) => [
        {
          name: 'Edit',
          onClick: setEditing,
        },
        // { name: 'Pin' },
        { name: 'Forward' },
        {
          name: clipboard.copied ? (
            <span className="text-success">Copied</span>
          ) : (
            'Copy'
          ),
          props: {
            href: '#',
          },
          onClick: e => {
            e.preventDefault();
            clipboard.copy(message.body);
          },
        },
        { name: 'Set reminder' },
      ]}
      messageable={{
        slug: 'general',
        name: 'general',
        color: '#abb8c3',
        bio: 'Gruppo dove ci siamo tutti!!',
        id: 783,
        createdAt: '2016-09-29T12:54:45.000Z',
        updatedAt: '2019-04-12T16:46:42.000Z',
        klass: 'Team',
        scope: 'teams',
        uid: 'team-783',
        isLoading: false,
        adminPath: '/dashboard/apps/teams/general',
        members: [
          {
            email: 'andrea.vanini@uidu.org',
            name: 'Andrea Vanini',
            firstName: 'Andrea',
            lastName: 'Vanini',
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: '1987-04-17',
            age: 31,
            phone: null,
            website: null,
            notes: null,
            gender: 'male',
            id: 1,
            createdAt: '2016-09-29T12:54:45.000Z',
            updatedAt: '2016-09-29T12:54:45.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-1',
            isLoading: false,
            avatar: {
              hasAvatar: true,
              default:
                '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
              thumb:
                '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
              big:
                '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
            },
            adminPath: '/dashboard/apps/contacts/1306',
            memberId: 1306,
            memberableId: 783,
            assignee: false,
            preferences: {},
            contact: 1306,
            contactId: 1306,
            networkId: 783,
          },
          {
            email: 'simobg@gmail.com',
            name: "Simone Dall'angelo",
            firstName: 'Simone',
            lastName: "Dall'angelo",
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: '1982-09-24',
            age: 36,
            phone: null,
            website: null,
            notes: null,
            gender: 'male',
            id: 4,
            createdAt: '2016-10-14T07:24:53.000Z',
            updatedAt: '2016-10-14T07:24:53.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-4',
            isLoading: false,
            avatar: {
              hasAvatar: true,
              default:
                '/uploads/contact/avatar/1625/default_simobg_gmail.com.jpg',
              thumb: '/uploads/contact/avatar/1625/thumb_simobg_gmail.com.jpg',
              big: '/uploads/contact/avatar/1625/big_simobg_gmail.com.jpg',
            },
            adminPath: '/dashboard/apps/contacts/1625',
            memberId: 1625,
            memberableId: 783,
            assignee: false,
            preferences: {},
            contact: 1625,
            contactId: 1625,
            networkId: 783,
          },
          {
            id: 6,
            memberId: 2174,
            memberableId: 783,
            role: 'admin',
            assignee: false,
            preferences: {},
            createdAt: '2016-10-20T10:16:13.000Z',
            updatedAt: '2016-10-20T10:16:13.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-6',
            isLoading: false,
            contact: 2174,
            contactId: 2174,
            networkId: 783,
          },
          {
            id: 162,
            memberId: 4237,
            memberableId: 783,
            role: 'admin',
            assignee: false,
            preferences: {},
            createdAt: '2017-02-20T17:17:00.000Z',
            updatedAt: '2017-02-20T17:17:00.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-162',
            isLoading: false,
            contact: 4237,
            contactId: 4237,
            networkId: 783,
          },
          {
            id: 163,
            memberId: 2176,
            memberableId: 783,
            role: 'admin',
            assignee: false,
            preferences: {},
            createdAt: '2017-02-20T17:19:25.000Z',
            updatedAt: '2017-02-20T17:19:25.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-163',
            isLoading: false,
            contact: 2176,
            contactId: 2176,
            networkId: 783,
          },
          {
            id: 164,
            memberId: 2177,
            memberableId: 783,
            role: 'admin',
            assignee: false,
            preferences: {},
            createdAt: '2017-02-20T17:21:32.000Z',
            updatedAt: '2017-02-20T17:21:32.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-164',
            isLoading: false,
            contact: 2177,
            contactId: 2177,
            networkId: 783,
          },
          {
            email: 'marco.ronchi+2@gmail.com',
            name: 'Marco Ronchi',
            firstName: 'Marco',
            lastName: 'Ronchi',
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: null,
            age: null,
            phone: null,
            website: null,
            notes: null,
            gender: null,
            id: 165,
            createdAt: '2017-02-20T17:22:32.000Z',
            updatedAt: '2017-02-20T17:22:32.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-165',
            isLoading: false,
            avatar: {
              hasAvatar: true,
              default:
                '/uploads/contact/avatar/2151/default_marco.ronchi%2B2_gmail.com.jpg',
              thumb:
                '/uploads/contact/avatar/2151/thumb_marco.ronchi%2B2_gmail.com.jpg',
              big:
                '/uploads/contact/avatar/2151/big_marco.ronchi%2B2_gmail.com.jpg',
            },
            adminPath: '/dashboard/apps/contacts/2151',
            memberId: 2151,
            memberableId: 783,
            assignee: false,
            preferences: {},
            contact: 2151,
            contactId: 2151,
            networkId: 783,
          },
          {
            email: 'sfortunato@gmail.com',
            name: 'Sfortunello Carino',
            firstName: 'Sfortunello',
            lastName: 'Carino',
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: null,
            age: null,
            phone: null,
            website: null,
            notes: null,
            gender: null,
            id: 166,
            createdAt: '2017-02-20T17:57:22.000Z',
            updatedAt: '2017-02-20T17:57:22.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-166',
            isLoading: false,
            avatar: {
              hasAvatar: true,
              default:
                '/uploads/contact/avatar/2152/default_sfortunato_gmail.com.jpg',
              thumb:
                '/uploads/contact/avatar/2152/thumb_sfortunato_gmail.com.jpg',
              big: '/uploads/contact/avatar/2152/big_sfortunato_gmail.com.jpg',
            },
            adminPath: '/dashboard/apps/contacts/2152',
            memberId: 2152,
            memberableId: 783,
            assignee: false,
            preferences: {},
            contact: 2152,
            contactId: 2152,
            networkId: 783,
          },
          {
            email: 'asdsandrea.vanini@uidu.org',
            name: 'Sddson Sadnasd',
            firstName: 'Sddson',
            lastName: 'Sadnasd',
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: null,
            age: null,
            phone: null,
            website: null,
            notes: null,
            gender: null,
            id: 167,
            createdAt: '2017-02-20T18:00:14.000Z',
            updatedAt: '2017-02-20T18:00:14.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-167',
            isLoading: false,
            avatar: {
              hasAvatar: true,
              default:
                '/uploads/contact/avatar/2153/default_asdsandrea.vanini_uidu.org.jpg',
              thumb:
                '/uploads/contact/avatar/2153/thumb_asdsandrea.vanini_uidu.org.jpg',
              big:
                '/uploads/contact/avatar/2153/big_asdsandrea.vanini_uidu.org.jpg',
            },
            adminPath: '/dashboard/apps/contacts/2153',
            memberId: 2153,
            memberableId: 783,
            assignee: false,
            preferences: {},
            contact: 2153,
            contactId: 2153,
            networkId: 783,
          },
          {
            email: 'alice.ghidoni@gmail.com',
            name: 'Alice Ghidoni',
            firstName: 'Alice',
            lastName: 'Ghidoni',
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: null,
            age: null,
            phone: null,
            website: null,
            notes: null,
            gender: null,
            id: 168,
            createdAt: '2017-02-20T18:22:27.000Z',
            updatedAt: '2017-02-20T18:22:27.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-168',
            isLoading: false,
            avatar: {
              hasAvatar: true,
              default:
                '/uploads/contact/avatar/2154/default_alice.ghidoni_gmail.com.jpg',
              thumb:
                '/uploads/contact/avatar/2154/thumb_alice.ghidoni_gmail.com.jpg',
              big:
                '/uploads/contact/avatar/2154/big_alice.ghidoni_gmail.com.jpg',
            },
            adminPath: '/dashboard/apps/contacts/2154',
            memberId: 2154,
            memberableId: 783,
            assignee: false,
            preferences: {},
            contact: 2154,
            contactId: 2154,
            networkId: 783,
          },
          {
            id: 169,
            memberId: 2178,
            memberableId: 783,
            role: 'admin',
            assignee: false,
            preferences: {},
            createdAt: '2017-02-20T18:25:16.000Z',
            updatedAt: '2017-02-20T18:25:16.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-169',
            isLoading: false,
            contact: 2178,
            contactId: 2178,
            networkId: 783,
          },
          {
            email: 'chiara.taddei2@gmail.com',
            name: 'Chiara Taddei',
            firstName: 'Chiara',
            lastName: 'Taddei',
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: null,
            age: null,
            phone: null,
            website: null,
            notes: null,
            gender: null,
            id: 170,
            createdAt: '2017-02-20T18:26:13.000Z',
            updatedAt: '2017-02-20T18:26:13.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-170',
            isLoading: false,
            avatar: {
              hasAvatar: true,
              default:
                '/uploads/contact/avatar/2155/default_chiara.taddei2_gmail.com.jpg',
              thumb:
                '/uploads/contact/avatar/2155/thumb_chiara.taddei2_gmail.com.jpg',
              big:
                '/uploads/contact/avatar/2155/big_chiara.taddei2_gmail.com.jpg',
            },
            adminPath: '/dashboard/apps/contacts/2155',
            memberId: 2155,
            memberableId: 783,
            assignee: false,
            preferences: {},
            contact: 2155,
            contactId: 2155,
            networkId: 783,
          },
          {
            email: 'simobg123@gmail.com',
            name: 'Simone 123',
            firstName: 'Simone',
            lastName: '123',
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: null,
            age: null,
            phone: '',
            website: null,
            notes: null,
            gender: null,
            id: 178,
            createdAt: '2017-03-29T09:00:58.000Z',
            updatedAt: '2017-03-29T09:00:58.000Z',
            klass: 'Member',
            scope: 'members',
            uid: 'member-178',
            isLoading: false,
            avatar: {
              hasAvatar: true,
              default:
                '/uploads/contact/avatar/2164/default_simobg123_gmail.com.jpg',
              thumb:
                '/uploads/contact/avatar/2164/thumb_simobg123_gmail.com.jpg',
              big: '/uploads/contact/avatar/2164/big_simobg123_gmail.com.jpg',
            },
            adminPath: '/dashboard/apps/contacts/2164',
            memberId: 2164,
            memberableId: 783,
            assignee: false,
            preferences: {},
            contact: 2164,
            contactId: 2164,
            networkId: 783,
          },
        ],
        lastMessage: {
          kind: 'message.create',
          id: 145644,
          createdAt: '2019-04-12T16:46:42.000Z',
          updatedAt: '2019-04-12T16:46:42.000Z',
          klass: 'Message',
          scope: 'messages',
          uid: 'message-145644',
          isLoading: false,
          body: '😜',
          unread: false,
          messager: {
            email: 'andrea.vanini@uidu.org',
            name: 'Andrea Vanini',
            firstName: 'Andrea',
            lastName: 'Vanini',
            nickname: null,
            fiscalCode: null,
            summary: null,
            displayName: null,
            role: 'admin',
            birthdate: '1987-04-17',
            age: 31,
            phone: null,
            website: null,
            notes: null,
            gender: 'male',
            id: 1306,
            createdAt: '2016-02-04T09:03:11.000Z',
            updatedAt: '2017-10-23T16:26:10.000Z',
            klass: 'Contact',
            scope: 'contacts',
            uid: 'contact-1306',
            isLoading: false,
            avatar: {
              has_avatar: true,
              default:
                '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
              thumb:
                '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
              big:
                '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
            },
            adminPath: '/dashboard/apps/contacts/1306',
          },
          itemable: null,
        },
        messages: {
          isFetching: false,
          didInvalidate: false,
          hasMore: true,
          messages: [
            {
              kind: 'message.create',
              id: 145644,
              createdAt: '2019-04-12T16:46:42.000Z',
              updatedAt: '2019-04-12T16:46:42.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145644',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: '😜',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145643,
              createdAt: '2019-04-12T16:42:43.000Z',
              updatedAt: '2019-04-12T16:42:43.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145643',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'funziona?',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145642,
              createdAt: '2019-04-12T16:42:39.000Z',
              updatedAt: '2019-04-12T16:42:39.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145642',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: '1',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145641,
              createdAt: '2019-04-12T16:28:05.000Z',
              updatedAt: '2019-04-12T16:28:05.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145641',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'ggg',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145640,
              createdAt: '2019-04-12T16:28:00.000Z',
              updatedAt: '2019-04-12T16:28:00.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145640',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'iii',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1200,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145635,
              createdAt: '2019-03-08T01:30:23.000Z',
              updatedAt: '2019-03-08T01:30:23.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145635',
              isLoading: false,
              attachments: [
                {
                  description: null,
                  id: 9015,
                  createdAt: '2019-03-08T01:30:23.000Z',
                  updatedAt: '2019-03-08T01:30:24.000Z',
                  klass: 'Attachment',
                  scope: 'attachments',
                  uid: 'attachment-9015',
                  isLoading: false,
                  blob: {
                    id: 1296,
                    key: 'd3wk7ssiDhXV2X7UB6CyKodV',
                    metadata: {
                      identified: true,
                      width: 2048,
                      height: 1365,
                      analyzed: true,
                    },
                    type: 'jpg',
                    name:
                      '46723137_714141122296014_3377779469480624128_o_714141115629348.jpg',
                    file:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEFGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--37653faade99b4cb42cc6c3d0725293fe049a403/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lJT0RBd0Jqb0dSVlE9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--923db1eaf57db3910fad44ce6c06c4d3c8620fac/46723137_714141122296014_3377779469480624128_o_714141115629348.jpg',
                    downloadUrl:
                      'https://uidu.local:8443/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEFGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--37653faade99b4cb42cc6c3d0725293fe049a403/46723137_714141122296014_3377779469480624128_o_714141115629348.jpg?disposition=attachment',
                    preview:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEFGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--37653faade99b4cb42cc6c3d0725293fe049a403/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lNTVRNeVhuZzRPQVk2QmtWVU9nNXBiblJsY214aFkyVkpJZ3BRYkdGdVpRWTdCbFE2REhGMVlXeHBkSGxwU3c9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--90cb4b2ee1be3c6f6799c146619c6a42405f883f/46723137_714141122296014_3377779469480624128_o_714141115629348.jpg',
                  },
                  kind: 'image',
                },
                {
                  description: null,
                  id: 9016,
                  createdAt: '2019-03-08T01:30:24.000Z',
                  updatedAt: '2019-03-08T01:30:24.000Z',
                  klass: 'Attachment',
                  scope: 'attachments',
                  uid: 'attachment-9016',
                  isLoading: false,
                  blob: {
                    id: 1294,
                    key: 'w57A6gq3wdm3uKiKLhyQ8MvQ',
                    metadata: {
                      identified: true,
                      width: 2048,
                      height: 1365,
                      analyzed: true,
                    },
                    type: 'jpg',
                    name:
                      '46732164_714142115629248_306334981859311616_o_714142112295915.jpg',
                    file:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzRGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--04804a85f09343005e358d31d9b3ea3c11db8dfe/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lJT0RBd0Jqb0dSVlE9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--923db1eaf57db3910fad44ce6c06c4d3c8620fac/46732164_714142115629248_306334981859311616_o_714142112295915.jpg',
                    downloadUrl:
                      'https://uidu.local:8443/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzRGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--04804a85f09343005e358d31d9b3ea3c11db8dfe/46732164_714142115629248_306334981859311616_o_714142112295915.jpg?disposition=attachment',
                    preview:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzRGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--04804a85f09343005e358d31d9b3ea3c11db8dfe/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lNTVRNeVhuZzRPQVk2QmtWVU9nNXBiblJsY214aFkyVkpJZ3BRYkdGdVpRWTdCbFE2REhGMVlXeHBkSGxwU3c9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--90cb4b2ee1be3c6f6799c146619c6a42405f883f/46732164_714142115629248_306334981859311616_o_714142112295915.jpg',
                  },
                  kind: 'image',
                },
                {
                  description: null,
                  id: 9017,
                  createdAt: '2019-03-08T01:30:24.000Z',
                  updatedAt: '2019-03-08T01:30:24.000Z',
                  klass: 'Attachment',
                  scope: 'attachments',
                  uid: 'attachment-9017',
                  isLoading: false,
                  blob: {
                    id: 1295,
                    key: 'R87D7UeT36JLgDKnRcD4c72t',
                    metadata: {
                      identified: true,
                      width: 2048,
                      height: 1365,
                      analyzed: true,
                    },
                    type: 'jpg',
                    name:
                      '46760247_714141785629281_5699958859251056640_o_714141782295948.jpg',
                    file:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzhGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f7a9d733a0faedb8144e046bc1018cd9d7a43a28/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lJT0RBd0Jqb0dSVlE9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--923db1eaf57db3910fad44ce6c06c4d3c8620fac/46760247_714141785629281_5699958859251056640_o_714141782295948.jpg',
                    downloadUrl:
                      'https://uidu.local:8443/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzhGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f7a9d733a0faedb8144e046bc1018cd9d7a43a28/46760247_714141785629281_5699958859251056640_o_714141782295948.jpg?disposition=attachment',
                    preview:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzhGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f7a9d733a0faedb8144e046bc1018cd9d7a43a28/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lNTVRNeVhuZzRPQVk2QmtWVU9nNXBiblJsY214aFkyVkpJZ3BRYkdGdVpRWTdCbFE2REhGMVlXeHBkSGxwU3c9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--90cb4b2ee1be3c6f6799c146619c6a42405f883f/46760247_714141785629281_5699958859251056640_o_714141782295948.jpg',
                  },
                  kind: 'image',
                },
                {
                  description: null,
                  id: 9018,
                  createdAt: '2019-03-08T01:30:24.000Z',
                  updatedAt: '2019-03-08T01:30:24.000Z',
                  klass: 'Attachment',
                  scope: 'attachments',
                  uid: 'attachment-9018',
                  isLoading: false,
                  blob: {
                    id: 1297,
                    key: 'psSa98qgcbjF1AA7V8gGWBfD',
                    metadata: {
                      identified: true,
                      width: 2048,
                      height: 1365,
                      analyzed: true,
                    },
                    type: 'jpg',
                    name:
                      '46786445_714142152295911_8794723979907563520_o_714142145629245.jpg',
                    file:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEVGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a866119c6d90810af54316258164e1479ee04b2/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lJT0RBd0Jqb0dSVlE9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--923db1eaf57db3910fad44ce6c06c4d3c8620fac/46786445_714142152295911_8794723979907563520_o_714142145629245.jpg',
                    downloadUrl:
                      'https://uidu.local:8443/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEVGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a866119c6d90810af54316258164e1479ee04b2/46786445_714142152295911_8794723979907563520_o_714142145629245.jpg?disposition=attachment',
                    preview:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEVGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a866119c6d90810af54316258164e1479ee04b2/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lNTVRNeVhuZzRPQVk2QmtWVU9nNXBiblJsY214aFkyVkpJZ3BRYkdGdVpRWTdCbFE2REhGMVlXeHBkSGxwU3c9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--90cb4b2ee1be3c6f6799c146619c6a42405f883f/46786445_714142152295911_8794723979907563520_o_714142145629245.jpg',
                  },
                  kind: 'image',
                },
              ],
              mentions: [],
              body:
                'Questo era vuoto ma non ho capito perchè, forse per gli allegati',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145627,
              createdAt: '2018-12-12T18:03:20.000Z',
              updatedAt: '2018-12-12T18:03:20.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145627',
              isLoading: false,
              attachments: [],
              mentions: [
                {
                  id: 38,
                  mentioneeType: 'Contact',
                  mentioneeId: 1628,
                },
              ],
              body: 'questo funziona [Giulia Sormani](Member:1628) ',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1200,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145626,
              createdAt: '2018-12-12T18:03:12.000Z',
              updatedAt: '2018-12-12T18:03:12.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145626',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'Finirà mai?',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145625,
              createdAt: '2018-12-12T18:03:08.000Z',
              updatedAt: '2018-12-12T18:03:08.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145625',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'Aiuto',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145620,
              createdAt: '2018-11-23T18:20:14.000Z',
              updatedAt: '2018-11-23T18:20:14.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145620',
              isLoading: false,
              attachments: [
                {
                  description: null,
                  id: 9014,
                  createdAt: '2018-11-23T18:20:14.000Z',
                  updatedAt: '2018-11-23T18:20:14.000Z',
                  klass: 'Attachment',
                  scope: 'attachments',
                  uid: 'attachment-9014',
                  isLoading: false,
                  blob: {
                    id: 1268,
                    key: 'iFuLhJP43GMkAgUh6KVSJW3H',
                    metadata: {
                      identified: true,
                      width: 586,
                      height: 158,
                      analyzed: true,
                    },
                    type: 'png',
                    name: 'Schermata 2018-11-22 alle 14.23.12.png',
                    file:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlFFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--753a6ea0cfc6795dafb6e2fc5c8e04221f571b58/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lJT0RBd0Jqb0dSVlE9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--923db1eaf57db3910fad44ce6c06c4d3c8620fac/Schermata%202018-11-22%20alle%2014.23.12.png',
                    downloadUrl:
                      'https://uidu.local:8443/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlFFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--753a6ea0cfc6795dafb6e2fc5c8e04221f571b58/Schermata%202018-11-22%20alle%2014.23.12.png?disposition=attachment',
                    preview:
                      'https://uidu.local:8443/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlFFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--753a6ea0cfc6795dafb6e2fc5c8e04221f571b58/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lNTVRNeVhuZzRPQVk2QmtWVU9nNXBiblJsY214aFkyVkpJZ3BRYkdGdVpRWTdCbFE2REhGMVlXeHBkSGxwU3c9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--90cb4b2ee1be3c6f6799c146619c6a42405f883f/Schermata%202018-11-22%20alle%2014.23.12.png',
                  },
                  kind: 'image',
                },
              ],
              mentions: [],
              body: 'Ma gli allegati come funzionao?',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145617,
              createdAt: '2018-10-08T22:33:07.000Z',
              updatedAt: '2018-10-08T22:33:07.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145617',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'Test nuovo messaggio',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145606,
              createdAt: '2018-10-03T14:26:08.000Z',
              updatedAt: '2018-10-03T14:26:08.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145606',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'Test creazione messaggio!',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 145601,
              createdAt: '2018-10-02T20:18:09.000Z',
              updatedAt: '2018-10-02T20:18:09.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145601',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'Test creazione messaggio ancora',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'network.update',
              id: 145583,
              createdAt: '2018-09-27T14:51:42.000Z',
              updatedAt: '2018-09-27T14:51:42.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145583',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: ' ha modificato bio in "Gruppo dove ci siamo tutti!!"',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: {
                id: 135168,
                schema: 'audits',
              },
            },
            {
              kind: 'message.create',
              id: 145578,
              createdAt: '2018-09-27T09:18:38.000Z',
              updatedAt: '2018-09-27T09:18:38.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145578',
              isLoading: false,
              attachments: [],
              mentions: [
                {
                  id: 36,
                  mentioneeType: 'Network',
                  mentioneeId: 783,
                },
                {
                  id: 37,
                  mentioneeType: 'Task',
                  mentioneeId: 1661,
                },
              ],
              body:
                'Aggiunho una mentions a [general](Network:783)  e a [Gestione membri nei gruppi](Task:1661) ',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'task.create',
              id: 145489,
              createdAt: '2018-09-13T14:29:55.000Z',
              updatedAt: '2018-09-13T14:29:55.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145489',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'task.create',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: {
                id: 1913,
                schema: 'tasks',
              },
            },
            {
              kind: 'task.create',
              id: 145456,
              createdAt: '2018-09-13T14:23:45.000Z',
              updatedAt: '2018-09-13T14:23:45.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-145456',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'task.create',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: null,
            },
            {
              kind: 'network.update',
              id: 144378,
              createdAt: '2018-09-10T13:53:52.000Z',
              updatedAt: '2018-09-10T13:53:52.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-144378',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: ' ha modificato name in "general"',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'andrea.vanini@uidu.org',
                name: 'Andrea Vanini',
                firstName: 'Andrea',
                lastName: 'Vanini',
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1987-04-17',
                age: 31,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1306,
                createdAt: '2016-02-04T09:03:11.000Z',
                updatedAt: '2017-10-23T16:26:10.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1306',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1306/default_andrea.vanini_uidu.org.jpg',
                  thumb:
                    '/uploads/contact/avatar/1306/thumb_andrea.vanini_uidu.org.jpg',
                  big:
                    '/uploads/contact/avatar/1306/big_andrea.vanini_uidu.org.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1306',
              },
              itemable: {
                id: 100941,
                schema: 'audits',
              },
            },
            {
              kind: 'message.create',
              id: 144291,
              createdAt: '2018-09-07T12:06:08.000Z',
              updatedAt: '2018-09-07T12:06:08.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-144291',
              isLoading: false,
              attachments: [],
              mentions: [
                {
                  id: 33,
                  mentioneeType: 'Contact',
                  mentioneeId: 1306,
                },
                {
                  id: 34,
                  mentioneeType: 'Contact',
                  mentioneeId: 1625,
                },
              ],
              body:
                "ragazzi [Andrea Vanini](Member:1306) [Simone Dall'angelo](Member:1625)  il problema è risolto ",
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'simobg@gmail.com',
                name: "Simone Dall'angelo",
                firstName: 'Simone',
                lastName: "Dall'angelo",
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1982-09-24',
                age: 36,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1625,
                createdAt: '2015-04-26T16:54:03.000Z',
                updatedAt: '2018-10-03T14:24:48.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1625',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1625/default_simobg_gmail.com.jpg',
                  thumb:
                    '/uploads/contact/avatar/1625/thumb_simobg_gmail.com.jpg',
                  big: '/uploads/contact/avatar/1625/big_simobg_gmail.com.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1625',
              },
              itemable: null,
            },
            {
              kind: 'message.create',
              id: 144279,
              createdAt: '2018-09-07T10:17:40.000Z',
              updatedAt: '2018-09-07T10:17:40.000Z',
              klass: 'Message',
              scope: 'messages',
              uid: 'message-144279',
              isLoading: false,
              attachments: [],
              mentions: [],
              body: 'poi una volta connesso va veloce',
              unread: false,
              messageable: {
                slug: 'general',
                name: 'general',
                color: '#abb8c3',
                bio: 'Gruppo dove ci siamo tutti!!',
                id: 783,
                createdAt: '2016-09-29T12:54:45.000Z',
                updatedAt: '2019-04-12T16:46:42.000Z',
                klass: 'Team',
                scope: 'teams',
                uid: 'team-783',
                isLoading: false,
                adminPath: '/dashboard/apps/teams/general',
              },
              messager: {
                email: 'simobg@gmail.com',
                name: "Simone Dall'angelo",
                firstName: 'Simone',
                lastName: "Dall'angelo",
                nickname: null,
                fiscalCode: null,
                summary: null,
                displayName: null,
                role: 'admin',
                birthdate: '1982-09-24',
                age: 36,
                phone: null,
                website: null,
                notes: null,
                gender: 'male',
                id: 1625,
                createdAt: '2015-04-26T16:54:03.000Z',
                updatedAt: '2018-10-03T14:24:48.000Z',
                klass: 'Contact',
                scope: 'contacts',
                uid: 'contact-1625',
                isLoading: false,
                avatar: {
                  has_avatar: true,
                  default:
                    '/uploads/contact/avatar/1625/default_simobg_gmail.com.jpg',
                  thumb:
                    '/uploads/contact/avatar/1625/thumb_simobg_gmail.com.jpg',
                  big: '/uploads/contact/avatar/1625/big_simobg_gmail.com.jpg',
                },
                adminPath: '/dashboard/apps/contacts/1625',
              },
              itemable: null,
            },
          ],
          lastUpdated: 1555087841689,
        },
      }}
    />
  );
}
