import { Schema } from 'prosemirror-model';
import { createSchema, SchemaConfig } from './create-schema';

export const defaultSchemaConfig: SchemaConfig = {
  nodes: [
    'doc',
    'paragraph',
    'text',
    'bulletList',
    'orderedList',
    'listItem',
    'heading',
    'blockquote',
    'codeBlock',
    'panel',
    'rule',
    'image',
    'mention',
    'media',
    'mediaGroup',
    'mediaSingle',
    'confluenceJiraIssue',
    'expand',
    'nestedExpand',
    'extension',
    'inlineExtension',
    'bodiedExtension',
    'hardBreak',
    'emoji',
    'table',
    'tableCell',
    'tableHeader',
    'tableRow',
    'decisionList',
    'decisionItem',
    'taskList',
    'taskItem',
    'unknownBlock',
    'date',
    'status',
    'placeholder',
    'layoutSection',
    'layoutColumn',
    'inlineCard',
    'blockCard',
    'unsupportedBlock',
    'unsupportedInline',
    'video',
  ],
  marks: [
    'link',
    'em',
    'strong',
    'strike',
    'subsup',
    'underline',
    'code',
    'textColor',
    'confluenceInlineComment',
    'breakout',
    'alignment',
    'indentation',
    'annotation',
    'unsupportedMark',
    'unsupportedNodeAttribute',
  ],
};

export const getSchemaBasedOnStage = (stage = 'final') =>
  createSchema(defaultSchemaConfig);

export const defaultSchema: Schema = getSchemaBasedOnStage();
