/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'fabric.mention.unknow.user.error': 'Neznámý uživatel {userId}',
  'fabric.mention.noAccess.warning':
    'Uživatel {name} nebude informován, protože nemá přístup',
  'fabric.mention.noAccess.label': 'Žádný přístup',
  'fabric.mention.error.defaultHeadline': 'Něco se pokazilo',
  'fabric.mention.error.defaultAction': 'Zkuste to znovu za pár sekund',
  'fabric.mention.error.loginAgain': 'Zkuste se odhlásit a znovu přihlásit',
  'fabric.mention.error.differentText': 'Zkuste zadat jiný text',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 člen} few{{0} členové} many{{0} členů} other{{0} členů}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{{0} členů včetně vás} few{{0} členů včetně vás} many{{0} členů včetně vás} other{{0} členů včetně vás}}',
  'fabric.elements.mentions.team.member.50plus': '50+ členů',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ členů včetně vás',
  'fabric.elements.mentions.team.mention.highlight.title': 'Zmiňte svůj tým',
  'fabric.elements.mentions.team.mention.highlight.description':
    'Informujte všechny jedním kliknutím. Nemáte tým?',
  'fabric.elements.mentions.team.mention.highlight.description.link':
    'Zadejte zmínku.',
  'fabric.elements.mentions.team.meantion.highlight.close.button.tooltip':
    'Zavřít',
};
