/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// German
export default {
  'fabric.mention.unknow.user.error': 'Unbekannter Benutzer {userId}',
  'fabric.mention.noAccess.warning':
    '{name} wird nicht benachrichtigt, da diese Person keinen Zugriff besitzt.',
  'fabric.mention.noAccess.label': 'Kein Zugriff',
  'fabric.mention.error.defaultHeadline': 'Irgendetwas ist schiefgelaufen',
  'fabric.mention.error.defaultAction':
    'Versuchen Sie es in ein paar Sekunden erneut.',
  'fabric.mention.error.loginAgain': 'Loggen Sie sich aus und wieder ein.',
  'fabric.mention.error.differentText':
    'Versuchen Sie, einen anderen Text einzugeben.',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{Ein Mitglied} other{{0} Mitglieder}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{{0} Mitglieder, inklusive Ihnen} other{{0} Mitglieder, einschließlich Ihnen}}',
  'fabric.elements.mentions.team.member.50plus': 'Mehr als 50 Mitglieder',
  'fabric.elements.mentions.team.member.50plus.including.you':
    'Mehr als 50 Mitglieder, einschließlich Ihnen',
  'fabric.elements.mentions.team.mention.highlight.title':
    'Erwähnen Sie Ihr Team',
  'fabric.elements.mentions.team.mention.highlight.description':
    'Holen Sie alle mit einem Klick an Bord. Noch kein Team?',
  'fabric.elements.mentions.team.mention.highlight.description.link':
    'Nehmen Sie die erste Erwähnung vor.',
  'fabric.elements.mentions.team.meantion.highlight.close.button.tooltip':
    'Schließen',
};
