/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Hungarian
export default {
  'fabric.mention.unknow.user.error': 'Ismeretlen felhasználó: {userId}',
  'fabric.mention.noAccess.warning':
    '{name} nem kap értesítést, mert nincs hozzáférése.',
  'fabric.mention.noAccess.label': 'Nincs hozzáférés',
  'fabric.mention.error.defaultHeadline': 'Hiba történt.',
  'fabric.mention.error.defaultAction':
    'Néhány másodperc múlva próbálja meg újból.',
  'fabric.mention.error.loginAgain':
    'Próbáljon meg kijelentkezni, majd újból bejelentkezni.',
  'fabric.mention.error.differentText': 'Próbáljon meg más szöveget beírni.',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 tag} other{{0} tag}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 tag, ideértve téged is} other{{0} tag, ideértve téged is}}',
  'fabric.elements.mentions.team.member.50plus': '50+ tag',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ tag, ideértve téged is',
  'fabric.elements.mentions.team.mention.highlight.title':
    'Említsd meg csapatodat',
  'fabric.elements.mentions.team.mention.highlight.description':
    'Egyetlen kattintással mindenkit felvehetsz az oldalra. Nincs csapatod?',
  'fabric.elements.mentions.team.mention.highlight.description.link':
    'Hozz létre egyet.',
  'fabric.elements.mentions.team.meantion.highlight.close.button.tooltip':
    'Bezárás',
};
