/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'fabric.mention.unknow.user.error': 'Nieznany użytkownik {userId}',
  'fabric.mention.noAccess.warning':
    'Użytkownicy: {name} nie zostaną powiadomieni, ponieważ nie mają dostępu',
  'fabric.mention.noAccess.label': 'Brak dostępu',
  'fabric.mention.error.defaultHeadline': 'Coś poszło nie tak',
  'fabric.mention.error.defaultAction': 'Spróbuj ponownie za chwilę',
  'fabric.mention.error.loginAgain':
    'Spróbuj się wylogować i zalogować ponownie',
  'fabric.mention.error.differentText': 'Spróbuj wpisać inny tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 użytkownik} few{{0} użytkowników} many{{0} użytkowników} other{{0} użytkownika}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{{0} użytkownika wliczając Ciebie} few{{0} użytkownika wliczając Ciebie} many{{0} użytkownika wliczając Ciebie} other{{0} użytkownika wliczając Ciebie}}',
  'fabric.elements.mentions.team.member.50plus': '50+ użytkowników',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ użytkowników wliczając Ciebie',
  'fabric.elements.mentions.team.mention.highlight.title':
    'Wspomniano Twój zespół',
  'fabric.elements.mentions.team.mention.highlight.description':
    'Przekieruj wszystkich na stronę za pomocą jednego kliknięcia. Nie masz zespołu?',
  'fabric.elements.mentions.team.mention.highlight.description.link':
    'Załóż go.',
  'fabric.elements.mentions.team.meantion.highlight.close.button.tooltip':
    'Odrzuć',
};
