/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Slovak
export default {
  'fabric.mention.unknow.user.error': 'Neznámy používateľ {userId}',
  'fabric.mention.noAccess.warning':
    'Používateľ {name} sa neupozorní. pretože nemá prístup',
  'fabric.mention.noAccess.label': 'Žiadny prístup',
  'fabric.mention.error.defaultHeadline': 'Vyskytol sa problém',
  'fabric.mention.error.defaultAction': 'Skúste to znova o chvíľu',
  'fabric.mention.error.loginAgain': 'Skúste sa odhlásiť a následne prihlásiť',
  'fabric.mention.error.differentText': 'Skúste zadať iný text',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 člen} few{{0} členovia} many{{0} členov} other{{0} členov}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{{0} členov vrátane vás} few{{0} členov vrátane vás} many{{0} členov vrátane vás} other{{0} členov vrátane vás}}',
  'fabric.elements.mentions.team.member.50plus': 'Viac ako 50 členov',
  'fabric.elements.mentions.team.member.50plus.including.you':
    'Viac ako 50 členov vrátane vás',
  'fabric.elements.mentions.team.mention.highlight.title': 'Spomenúť tím',
  'fabric.elements.mentions.team.mention.highlight.description':
    'Informujte každého jedným kliknutím. Nemáte tím?',
  'fabric.elements.mentions.team.mention.highlight.description.link':
    'Vytvoriť.',
  'fabric.elements.mentions.team.meantion.highlight.close.button.tooltip':
    'Zrušiť',
};
